#include <weapons.h>

const Weapon g_akimbo = {
    .name = "Akimbo Uzi",
    .src = "weapon_10",
    .icon = "icon_10",
    .secondary = 0,
    .no_spread = 0,
    .akimbo = 1,
    .no_aim = 1,
    .no_auto = 0,
    .melee = 0,
    .equipment = 0,
    .ammo = 18,
    .swap_time = 0.3f,
    .reload_time = 1.3f,
    .aim_speed = 0.12f,
    .speed_mlt = 1.04f,
    .damage = 14.0f,
    .headshot_mlt = 1.5f,
    .pierce = 1.0f,
    .range = 700.0f,
    .damage_drop = 13.0f,
    .rate = 0.07f,
    .spread = 40.0f,
    .min_spread = 10.0f,
    .recoil = 0.0034f,
    .recover = 0.978f,
    .recover_y = 0.996f,
    .recover_f = 0.975f,
    .zoom = 1.5f,
};

// {
// name: "Akimbo Uzi",
// src: "weapon_10",
// icon: "icon_10",
// sound: "weapon_10",
// secondary: false,
// nAuto: false,
// noAo: true,
// physRang: 0,
// physPow: 0,
// altSkin: {
// name: "Nova Uzi",
// mid: 0,
// midT: 0,
// blocked: true,
// noSale: true,
// weapon: 10,
// rarity: 0,
// seas: 3
// },
// nInsp: true,
// noAim: true,
// akimbo: true,
// type: 0,
// swapTime: 300,
// aimSpd: 120,
// spdMlt: 1.04,
// ammo: 18,
// reload: 1300,
// dmg: 14,
// hsMlt: 1.5,
// pierce: 1,
// range: 700,
// dmgDrop: 13,
// scale: 0.9,
// rightHoldY: -0.55,
// leftHoldZ: 0.2,
// leftHoldX: -0.1,
// leftHoldY: -0.55,
// rightHoldZ: 0.2,
// rightHoldX: -0.1,
// holdW: 1.3,
// xOff: 1.5,
// yOff: -0.95,
// zOff: -3.3,
// xOrg: 0,
// yOrg: -0.62,
// zOrg: -2.5,
// zLnM: 0.4,
// cLean: 0.1,
// cRot: 0.1,
// cDrop: 0.2,
// caseYOff: -0.15,
// caseZOff: -0.4,
// muzOff: 3.6,
// rate: 70,
// spread: 40,
// noSpread: false,
// movSpread: 0.1,
// minSpread: 10,
// zoom: 1.5,
// recoil: 0.0034,
// recoilR: 0.015,
// leanMlt: 0.6,
// recover: 0.978,
// recoverY: 0.996,
// recoverF: 0.975,
// recoilZ: 5,
// recoilYM: 0.7,
// recoilAnim: {
// recoilTweenY: 0.01
// },
// expScale: 0.7,
// rumble: 0.4,
// icnPad: -4
// }