#include <weapons.h>

const Weapon g_alien_blaster = {
    .name = "Alien Blaster",
    .src = "weapon_12",
    .icon = "icon_12",
    .secondary = 1,
    .no_spread = 0,
    .akimbo = 0,
    .no_aim = 0,
    .no_auto = 1,
    .melee = 0,
    .equipment = 0,
    .ammo = 4,
    .swap_time = 0.2f,
    .reload_time = 1.5f,
    .aim_speed = 0.12f,
    .speed_mlt = 1.0f,
    .damage = 50.0f,
    .headshot_mlt = 1.5f,
    .pierce = 0.85f,
    .range = 700.0f,
    .damage_drop = 10.0f,
    .rate = 0.17f,
    .spread = 150.0f,
    .recoil = 0.006f,
    .recover = 0.98f,
    .recover_y = 0.99f,
    .recover_f = 0.98f,
    .zoom = 1.4f,
};

// {
// name: "Alien Blaster",
// src: "weapon_12",
// icon: "icon_12",
// sound: "weapon_12",
// akimbo: false,
// noSpread: false,
// noAim: false,
// noAo: true,
// physRang: 0,
// physPow: 0,
// secondary: true,
// nRing: true,
// nAuto: true,
// transp: true,
// nCase: true,
// minRec: 50,
// kill: ["", 50],
// type: 1,
// swapTime: 200,
// aimSpd: 120,
// spdMlt: 1,
// ammo: 4,
// reload: 1500,
// dmg: 50,
// hsMlt: 1.5,
// pierce: 0.85,
// dmgDrop: 10,
// scale: 1.1,
// leftHoldY: -1,
// rightHoldY: -0.65,
// leftHoldZ: -0.2,
// rightHoldZ: -0.2,
// holdW: 1,
// xOff: 1.3,
// yOff: -0.83,
// zOff: -4.1,
// xOrg: 0,
// yRot: -0.01,
// yOrg: -0.53,
// zOrg: -3.8,
// cLean: 0.2,
// cRot: 0.2,
// cDrop: 0,
// inspectR: 0.1,
// inspectM: 0.8,
// muzOff: 2.2,
// muzOffY: 0.1,
// muzID: 3,
// muzMlt: 1.1,
// jYMlt: 0.8,
// range: 700,
// rate: 170,
// spread: 150,
// zoom: 1.4,
// leanMlt: 1.6,
// recoil: 0.006,
// recoilR: 0.01,
// recover: 0.98,
// recoverY: 0.99,
// recoverF: 0.98,
// recoilYM: 0.2,
// recoilZ: 2.2,
// aimRecMlt: 0.3,
// recoilAnim: {
// time: 200,
// recoilTweenY: 0.32
// },
// rumble: 0.4,
// icnPad: -8,
// expScale: 1.85
// }